import { oneLineTrim } from 'common-tags';

// The U.S. Department of State's Critical Language Scholarship (CLS) Program's
// 15 languages deemed crucial to national security and economic competitiveness.
// source: https://exchanges.state.gov/cls

// note: French, German, and Spanish added for demo purposes
// note: About sections generated by GitHub Copilot

export interface Language {
  name: string;
  about: string;
  selected?: boolean;
}

export const languages: Language[] = [
  {
    name: 'Arabic',
    about: oneLineTrim`
        Arabic is the official language of more than 20 countries and is spoken by more
        than 280 million people worldwide. It's also the liturgical language of Islam,
        which is followed by more than 1.6 billion people.
      `,
  },
  {
    name: 'Azerbaijani',
    about: oneLineTrim`
      Azerbaijani is the official language of Azerbaijan and is spoken by more than
      30 million people worldwide. It's also spoken in parts of Iran and Russia.
    `,
  },
  {
    name: 'Bangla',
    about: oneLineTrim`
      Bangla is the official language of Bangladesh and is also spoken in parts of India.
      It's the seventh most commonly spoken language in the world, with more than 200 million
      native speakers.
    `,
  },
  {
    name: 'Chinese',
    about: oneLineTrim`
      Chinese is the most commonly spoken language in the world, with more than 1.2 billion
      native speakers. It's also one of the most commonly studied languages in the United States.
    `,
  },
  {
    name: 'French',
    about: oneLineTrim`
      French is the official language of 29 countries and is spoken by more than 220 million
      people worldwide. It's also one of the most commonly studied languages in the United States.
    `,
  },
  {
    name: 'German',
    about: oneLineTrim`
      German is the official language of Germany and Austria and is one of the official
      languages of Switzerland. It's spoken by more than 100 million people worldwide.
    `,
  },
  {
    name: 'Hindi',
    about: oneLineTrim`
      Hindi is the official language of India and is spoken by more than 500 million people
      worldwide. It's also one of the most commonly spoken languages in the world.
    `,
  },
  {
    name: 'Indonesian',
    about: oneLineTrim`
      Indonesian is the official language of Indonesia and is spoken by more than 43 million
      people worldwide. It's also spoken in parts of Malaysia. It's the 23rd most commonly
      spoken language in the world.
    `,
  },
  {
    name: 'Japanese',
    about: oneLineTrim`
      Japanese is the official language of Japan and is spoken by more than 125 million people
      worldwide. It's also one of the most commonly studied languages in the United States.
    `,
  },
  {
    name: 'Korean',
    about: oneLineTrim`
      Korean is the official language of North and South Korea and is spoken by more than 78
      million people worldwide. It's also one of the most commonly studied languages in the
      United States.
    `,
  },
  {
    name: 'Persian',
    about: oneLineTrim`
      Persian is the official language of Iran and is spoken by more than 110 million people
      worldwide. It's also spoken in parts of Afghanistan and Tajikistan.
    `,
  },
  {
    name: 'Portuguese',
    about: oneLineTrim`
      Portuguese is the official language of Portugal and Brazil and is spoken by more than
      200 million people worldwide. It's also spoken in parts of Africa and Asia.
    `,
  },
  {
    name: 'Punjabi',
    about: oneLineTrim`
      Punjabi is the official language of Pakistan and is spoken by more than 100 million
      people worldwide. It's also spoken in parts of India.
    `,
  },
  {
    name: 'Russian',
    about: oneLineTrim`
      Russian is the official language of Russia and is spoken by more than 150 million
      people worldwide. It's also spoken in parts of Eastern Europe and Central Asia.
    `,
  },
  {
    name: 'Spanish',
    about: oneLineTrim`
      Spanish is the official language of more than 20 countries and is spoken by more
      than 400 million people worldwide. It's also one of the most commonly spoken
      languages in the United States.
    `,
  },
  {
    name: 'Swahili',
    about: oneLineTrim`
      Swahili is the official language of Tanzania and is spoken by more than 100 million
      people worldwide. It's also spoken in parts of Kenya, Uganda, and the Democratic
      Republic of the Congo.
    `,
  },
  {
    name: 'Turkish',
    about: oneLineTrim`
      Turkish is the official language of Turkey and is spoken by more than 70 million
      people worldwide. It's also spoken in parts of Europe and Central Asia.
    `,
  },
  {
    name: 'Urdu',
    about: oneLineTrim`
      Urdu is the official language of Pakistan and is spoken by more than 100 million
      people worldwide. It's also spoken in parts of India.
    `,
  },
];
